### PR TITLE
WDP200303-13

### PR DESCRIPTION
**Pull request by ichtys77**
I add swipe component by using swipe-react-component package. This solution can be used for all react components by wrapping.

**IMPORTANT NOTICE!** If you code same tests with using this component remember to put to test this line:
jest.mock('../../common/SwipeComponent/SwipeComponent', () => 'SwipeComponent')

### CODE REVIEW

**Comment by Varenthein** [comment]
Resolve conflicts and we are good to go :)

**Comment by ichtys77** [comment]
done

**Comment by Varenthein** [comment]
There are new conflicts to resolve

**Comment by ichtys77** [comment]
done... again

**Pull request merged**
