### PR TITLE
WDP 200303-8

### PR DESCRIPTION
**Pull request by morormo**
Fix incorrect variable name

### CODE REVIEW

**Comment by Varenthein** [comment]
`Fix incorrect variable name`? that's all? I think that this task should do a bit more ;)

**Comment by morormo** [comment]
TO DO:
-adding new variables so that the customer can edit the page

Done: 
-Add new variables to settings.scss
-Add new variables to components
-Separating main variables in settings.scss

**Comment by Varenthein** [comment]
Please resolve conflicts

**Comment by morormo** [comment]
TO DO
-change the variable

Done:
-I changed the button variable

**Pull request merged**
