### PR TITLE
Wdp200303 19

### PR DESCRIPTION
**Pull request by AnnaKuszal**
# No products in other categories; no effects on changing categoriss&pages;
* Added many products to fill in the other categories;
* Installed react-transition-group to manage transitions
*Added transition code to New Furniture component & add transition classes to 'styles'

Pages&categories change with animation.

### CODE REVIEW

**Comment by Varenthein** [comment]
Please resolve conflicts and we are good to go

**Comment by Varenthein** [comment]
There are new conflicts to resolve

**Comment by Varenthein** [comment]
@ichtys77 Review request.

**Comment by ichtys77** [comment]
Maybe You can fade view in component from old to new one. I try to explain, when i clicked next slide (or change category) app loaded products in component but previous view (with 'old' products) go below. On screen I see (for example) 16 products. You can consider animation without change height of NewFurniture component.

**Comment by AnnaKuszal** [comment]
> @AnnaKuszal Maybe You can fade view in component from old to new one. I try to explain, when i clicked next slide (or change category) app loaded products in component but previous view (with 'old' products) go below. On screen I see (for example) 16 products. You can consider animation without change height of NewFurniture component.

Lukasz, could you please send the screen of the NewFurniture  view you get after loading new page/category?

**Comment by ichtys77** [comment]
https://1drv.ms/v/s!AhF11bh4PZD-pQ9-Iz3U_W-2QqNl?e=6GucIC
it's video, let me know if You have any issues with this link

**Comment by AnnaKuszal** [comment]
I've succeded to fix the transition effect.

**Comment by AnnaKuszal** [comment]
The issue was tu set 'exit' on false in <CssTransition> tag. Łukasz, thanks for indicating the bug.

**Comment by AnnaKuszal** [comment]
Added cursor pointer to category links, resolved conflicts.

**Pull request merged**
