### PR TITLE
WDP20030312

### PR DESCRIPTION
**Pull request by jurecki**
- compare products function has been added
- new component: Sticky Bar has been added
- After click on "compare" button, product has been added to Sticky Bar
- User can remove products from "compare" by click "X" (after :hover)
- After refresh page, no products have "compare" button active

### CODE REVIEW

**Comment by Varenthein** [comment]
Please add a proper description.

**Comment by jurecki** [comment]
conflicts resolved

**Comment by jurecki** [comment]
I don't know why, but I've added wrong files...

**Comment by Varenthein** [comment]
Please resolve conflicts

**Pull request merged**
